services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: chat-app
    volumes:
      - ./src:/var/www/html
      - storage_data:/var/www/html/storage
      - cache_data:/var/www/html/bootstrap/cache
    working_dir: /var/www/html
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: chatapp
      DB_USERNAME: chatuser
      DB_PASSWORD: chatpass

  db:
    image: mysql:8.0
    container_name: chat-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: chatapp
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:alpine
    container_name: chat-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  reverb:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: chat-reverb
    working_dir: /var/www/html
    command: php artisan reverb:start --host=0.0.0.0 --port=6001
    volumes:
      - ./src:/var/www/html
      - storage_data:/var/www/html/storage
      - cache_data:/var/www/html/bootstrap/cache
    depends_on:
      - app
    ports:
      - "6001:6001"

volumes:
  db_data:
  storage_data:
  cache_data:
